#
# Defines environment variables.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Ensure that a non-login, non-interactive shell has a defined environment.
if [[ ( "$SHLVL" -eq 1 && ! -o LOGIN ) && -s "${ZDOTDIR:-$HOME}/.zprofile" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprofile"
fi

if (( $+commands[bat] )); then
  # use bat for man pages
  export MANPAGER="sh -c 'col -bx | bat -l man -p'"
  # use seti-classic theme for bat
  export BAT_THEME="seti-classic-vscode"
fi

if [[ -a "${ZDOTDIR:-$HOME}/.proxy" ]]; then
  source "${ZDOTDIR:-$HOME}/.proxy"
fi

if (( $+commands[emacs] )); then
  path+=("${ZDOTDIR:-$HOME}/.emacs.d/bin")
  export PATH
fi
