#
# Defines environment variables.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Ensure that a non-login, non-interactive shell has a defined environment.
if [[ ( "$SHLVL" -eq 1 && ! -o LOGIN ) && -s "${ZDOTDIR:-$HOME}/.zprofile" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprofile"
fi

if (( $+commands[bat] )); then
  # use bat for man pages
  export MANPAGER="sh -c 'col -bx | bat -l man -p'"
  # use seti-classic theme for bat
  export BAT_THEME="seti-classic-vscode"
fi

if [[ -a "${ZDOTDIR:-$HOME}/.proxy" ]]; then
  source "${ZDOTDIR:-$HOME}/.proxy"
fi

if (( $+commands[emacs] )); then
  path+=("${ZDOTDIR:-$HOME}/.emacs.d/bin")
  export PATH
fi

## Haskell Development

# cabal
if [ -d "${ZDOTDIR:-$HOME}/.cabal" ]; then
  # prepend before `/usr/bin` so it prefers user level over system level
  path=("${ZDOTDIR:-$HOME}/.cabal/bin" $path)
  export PATH
fi

# ghcup
if [ -d "${ZDOTDIR:-$HOME}/.ghcup" ]; then
  # prepend before `/usr/bin` so it prefers user level over system level
  path=("${ZDOTDIR:-$HOME}/.ghcup/bin" $path)
  export PATH
fi

## .NET Development

# dotnet
if [ -d "${ZDOTDIR:-$HOME}/.dotnet/tools" ]; then
  path+=("${ZDOTDIR:-$HOME}/.dotnet/tools")
  export PATH
fi

## Local Environment

# source system specific environment variables and computer specific configuration
if [[ -a "${ZDOTDIR:-$HOME}/.environment" ]]; then
  source "${ZDOTDIR:-$HOME}/.environment"
fi

# Tell things to sort by C
export LC_COLLATE=C

if (( $+commands[delta] )); then
  function diff() {
    cat "$1" | delta
  }
fi
