#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Customize to your needs...

if (( $+commands[batman] )); then
  alias man="batman $@"
fi

if (( $+commands[exa] )); then
  alias ls="exa -la --header --git --group"
  alias la="ls -la"
fi

if (( $+commands[hstr] )); then
  # HSTR configuration - add this to ~/.zshrc
  alias hh=hstr                    # hh to be alias for hstr
  setopt histignorespace           # skip cmds w/ leading space from history
  export HSTR_CONFIG=hicolor,prompt-bottom       # get more colors
  bindkey -s "\C-r" "\C-a hstr -- \C-j"     # bind hstr to Ctrl-r (for Vi mode check doc)
fi

[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh

function ff(){
  sudo find $@ 2>&1 | grep -v "Permission denied"
}

function jcurl(){
  curl -s "$@" | json_pp | pygmentize -l json
}

if $(cat /proc/version | grep -q "microsoft"); then
  # WSL
  alias clip=clip.exe
  alias nmap='"/mnt/c/Program Files (x86)/Nmap/nmap.exe"'
  export DISPLAY=$(cat /etc/resolv.conf | grep nameserver | awk '{print $2; exit;}'):0.0
fi

if [ -f /usr/local/bin/virtualenvwrapper.sh ]; then
  export VIRTUALENVWRAPPER_PYTHON=/usr/bin/python3
  export WORKON_HOME=$HOME/.virtualenvs
  source /usr/local/bin/virtualenvwrapper.sh
fi

if (( $+commands[grc] )); then
  alias ps="command grc ps"
fi


if (( $+commands[dotnet] )); then
  # zsh parameter completion for the dotnet CLI
  _dotnet_zsh_complete()
  {
    local completions=("$(dotnet complete "$words")")

    # If the completion list is empty, just continue with filename selection
    if [ -z "$completions" ]
    then
      _arguments '*::arguments: _normal'
      return
    fi

    # This is not a variable assignment, don't remove spaces!
    _values = "${(ps:\n:)completions}"
  }

  compdef _dotnet_zsh_complete dotnet
fi
